### ISSUE TITLE
Force-directed graph (networks)

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#11]

**Comment by AFFogarty** [comment]
Lookin' good...

![screen shot 2016-01-15 at 2 06 30 pm](https://cloud.githubusercontent.com/assets/2154530/12362486/9601ec10-bb91-11e5-932e-eecbaedb6988.png)

**Comment by musicus** [comment]
So sweet!

**Comment by AFFogarty** [comment]
Arrow heads.  Self-loops need to be fixed.

![screen shot 2016-01-15 at 2 56 33 pm](https://cloud.githubusercontent.com/assets/2154530/12363694/37e031d0-bb98-11e5-91b2-0ada51231f18.png)

**Comment by AFFogarty** [comment]
Coloured arrows.
![screen shot 2016-01-15 at 4 14 45 pm](https://cloud.githubusercontent.com/assets/2154530/12365485/2b03087e-bba3-11e5-965b-1f1855743fa0.png)

**Comment by musicus** [comment]
Awesome! Make sure that the arrows just barely touch the nodes, and do not get stalled up by the nodes.

**Comment by AFFogarty** [comment]
Yay endpoints!

![screen shot 2016-01-15 at 4 55 47 pm](https://cloud.githubusercontent.com/assets/2154530/12366385/e1bc6cc2-bba8-11e5-8e6c-f6d4f803c4dc.png)

**Comment by AFFogarty** [comment]
The problem was that nodes with no outgoing edges were being ignored.

**Comment by musicus** [comment]
Ok. Ausgezeichnet.

**Comment by AFFogarty** [comment]
Going to close this ticket because we're using individual tickets for individual tasks.

**Comment by musicus** [comment]
_Okiedokie_.
