### ISSUE TITLE
Visualization Types

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#2]
What types of visualizations do we want to have?

**Comment by musicus** [comment]
We need bar graphs, clustered bar graphs, heat maps, circle packing, bubble charts, chord diagrams, dendrograms, force-directed graph (networks), node-link tree, zoomable pack layout, collapsible force layout, co-occurrence matrix, labeled force layout, trees. All of them should be zoomable, and searchable on the page that they are built. In addition the force directed charts should have nodes and edges scaled according to frequency (of the data).

**Comment by AFFogarty** [comment]
Ok, I'll create issues for all of these.

**Comment by musicus** [comment]
Cool! :+1:
