### ISSUE TITLE
Force directed charts should have nodes and edges scaled according to frequency (of the data).

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#24]

**Comment by AFFogarty** [comment]
What is "frequency"?

**Comment by musicus** [comment]
Frequency clearly is a misnomer here. What I mean is the probability number value of the edges. The way that you scaled the edges, or made them lighter or darker: the less frequently connected nodes should be further away from the network overall, while the more frequently connected nodes should be clustered closer together.

**Comment by AFFogarty** [comment]
Implemented in 79cf5c7f4dcdb4538d304aabdc571f8ebc253bd3
