### ISSUE TITLE
Colour-blind colour scheme for heat maps

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#29]
We should have a colour-blind friendly colour scheme option for the heat maps.

**Comment by musicus** [comment]
Yes, always a good idea!

**Comment by AFFogarty** [comment]
![screen shot 2016-01-21 at 11 48 06 am](https://cloud.githubusercontent.com/assets/2154530/12487384/f28d1fe8-c034-11e5-897b-bf75e420249d.png)

**Comment by musicus** [comment]
Very clear :+1:.

**Comment by AFFogarty** [comment]
A side effect of working on this is that the Heat Map now supports as many colour palettes as we want.

**Comment by musicus** [comment]
Great side effect!
