### ISSUE TITLE
Searchable Force Layout

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#32]

**Comment by musicus** [comment]
Let me clarify: For example I want to search for pitch class (PC) 6, then PC 6 and all of its connections (first level nodes/edges, i.e.: 6 => 7, or 6 => 5, etc.) will be highlighted, by reducing the alpha on all other nodes and edges. Of course it would be cool to have reduced alpha according to hierarchical level of "connectedness".

**Comment by AFFogarty** [comment]
Yeah, that's how I imagined it.

**Comment by musicus** [comment]
Gut (since I speak German translated into English).

**Comment by AFFogarty** [comment]
Actually, I think that reduced levels of opacity for connectedness will get confusing, because it will be hard to distinguish low degrees of connectedness from non-connected nodes.

**Comment by musicus** [comment]
Ok, let's just start with two levels of opacity.
