### ISSUE TITLE
Piano Roll.

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/VIS-Ualizer#41]
This will spawn probably a series of other issues: There should be a piano roll. Here is an [example](http://josquin.stanford.edu/cgi-bin/jrp?a=proll&id=Jos1511). It'd be great if one could zoom into specific sections, and of course scrolling (perhaps animated).

**Comment by musicus** [comment]
I added a [JSON piano roll file](https://github.com/ELVIS-Project/VIS-Ualizer/blob/master/data/json/Domine_non_secundum_peccata.json) from which a [piano roll image](https://github.com/ELVIS-Project/VIS-Ualizer/blob/master/data/images/Domine_non_secundum_peccata.png?raw=true) should be generated:

<img src="https://github.com/ELVIS-Project/VIS-Ualizer/blob/master/data/images/Domine_non_secundum_peccata.png?raw=true">

**Comment by AFFogarty** [comment]
We need a grid, zoom, and data labels.

**Comment by musicus** [comment]
:+1:
