### ISSUE TITLE
Clustered Bar Graphs

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#5]

**Comment by AFFogarty** [comment]
I'm starting to get the hang of how D3.js works.

![screen shot 2016-01-04 at 3 48 45 pm](https://cloud.githubusercontent.com/assets/2154530/12100101/cb46a144-b2fa-11e5-95a6-daef75dec5d8.png)

**Comment by musicus** [comment]
Looks Great - ez as π! D3 is awesome.  :+1:
