### ISSUE TITLE
Bad perf in Firefox

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#56]
Right now, the performance (especially for the Force-Directed Graph) is much worse on Firefox than on Chrome.

I did some Googling and it seems that updating vector attributes is generally slower on Firefox.  I am going to investigate possible optimization strategies.

**Comment by musicus** [comment]
(Force directed graphs weren't working at all for me from a version I downloaded this morning ... no graphs built.)

**Comment by AFFogarty** [comment]
That was a separate issue that I already fixed.

**Comment by musicus** [comment]
:neckbeard:

**Comment by AFFogarty** [comment]
So it turns out that opacity really kills performance in Firefox.

**Comment by musicus** [comment]
Make opacity conditional? Turn it off for Firefox, and change the colors as if they were opaque. 

But how much slower really is it? And is it something that will be addressed by later releases of Firefox? Maybe we should just provide a warning to Firefox users?
