### ISSUE TITLE
Piano Roll Piano Keys Toggle

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/VIS-Ualizer#57]
It would be great to have piano keys as background highlights (see image):

![screen shot 2016-03-10 at 11 30 20 am](https://cloud.githubusercontent.com/assets/1203470/13677678/05dfaa52-e6b9-11e5-8e4f-56ec8342d189.png)

**Comment by AFFogarty** [comment]
:musical_keyboard:

**Comment by musicus** [comment]
:+1: :musical_keyboard:

**Comment by AFFogarty** [comment]
![screen shot 2016-03-11 at 12 30 10 pm](https://cloud.githubusercontent.com/assets/2154530/13710046/185429b6-e785-11e5-808c-39e873c8eb04.png)

**Comment by musicus** [comment]
So sweet :neckbeard: :musical_keyboard: !

**Comment by AFFogarty** [comment]
We should add outlines to the note shapes so that consecutive notes of the same pitch and voice are distinguishable.

**Comment by musicus** [comment]
:+1: I'm down.
