### ISSUE TITLE
Heat Maps

### ISSUE THREAD

**Issue by AFFogarty** [ELVIS-Project/VIS-Ualizer#6]

**Comment by AFFogarty** [comment]
What kind of data would be in a heat map?

**Comment by musicus** [comment]
The heat map is something Alex Morgan has previously used. I'll get data from him.

**Comment by musicus** [comment]
I uploaded a heat map sample [csv file](https://github.com/ELVIS-Project/VIS-Ualizer/blob/master/data/non-truncated/Heatmap-Sample-Data.csv). Enjoy! (I will still try to get data from Alex M.).

**Comment by AFFogarty** [comment]
:+1:

**Comment by AFFogarty** [comment]
![screen shot 2016-01-19 at 4 58 42 pm](https://cloud.githubusercontent.com/assets/2154530/12433252/fcaf0a8a-becd-11e5-9167-7c19b726d04f.png)

**Comment by musicus** [comment]
Yes!
