### ISSUE TITLE
Sorting on bar graph page doesn't work in Firefox

### ISSUE THREAD

**Issue by vee-L** [ELVIS-Project/VIS-Ualizer#76]
This problem was not reproducible on Chrome and Safari, only on Firefox. No error appears to be returned, but the graph cannot be sorted in any way.

**Comment by musicus** [comment]
ok - @vee-L!

**Comment by vee-L** [comment]
UPDATE: also happens when trying to sort the pie chart. It seems that only sorting is broken, because other selections like heatmap color work.

**Comment by musicus** [comment]
Good.
