### ISSUE TITLE
Create a score display tool that integrates Verovio

### ISSUE THREAD

**Issue by vee-L** [ELVIS-Project/VIS-Ualizer#77]
Create another tab/tool in visualizer that uses Verovio to display music notation data "intelligently", and allows displaying patterns found in scores and playing them.

**Comment by vee-L** [comment]
Right now, the basic displaying of the score and playing,pausing and stopping the music all work, as well as highlighting what's currently being played (in blue). Should it have all the same functionality as piano roll, more, less? (to generate the midi, it converts the provided mei file  into a base64 string that's playable by the midi player, so no "real" midi file is being created).

**Comment by musicus** [comment]
Great, and yes. We have to also figure out how we can convert a score represented as a pandas dataframe in MEI, so Verovio can read it.

**Comment by vee-L** [comment]
Wouldn't that be done inside VIS?

**Comment by vee-L** [comment]
Warning to anyone (I don't know where I should post this) using midi.js : their current midi.player has a pretty severe bug that causes the first note not to be played, and the currently suggested fix on the issue page causes the player to not really terminate somehow, thus eventually crashing the browser (it seemed to work for some people but not for me). I _think_ I fixed it, I'll make a comment on the issue and possibly a pull request on their page if the suggested fix is also not enough for more than just me. Also I think the notes are getting doubled and there doesn't seem to be a fix for that that :(
