### ISSUE TITLE
Bar chart ascending order doesn't sort properly

### ISSUE THREAD

**Issue by vee-L** [ELVIS-Project/VIS-Ualizer#80]
Specifically when sorting by value in ascending order, there are few bars of the graph in the wrong spots.

**Comment by vee-L** [comment]
The deeper I get in this the weirder it gets. I've submitted it to StackOverFlow after narrowing down to an attribute that gets wonky, I'll report back if I get something.

**Comment by musicus** [comment]
Great.

**Comment by vee-L** [comment]
I appear to have fixed it, I'll just implement javascript unit testing properly before pushing it (also because the apparent source of the bug is just as weird as the last one).

**Comment by musicus** [comment]
Ausgezeichnet! As soon as you are done with the unit tests you can close this ticket.
😸

**Comment by vee-L** [comment]
Unit testing with d3 is awkward, there is an issue about implementing coherent javascript unit testing in elvis db, I might add one here as well because it all feels very hacky.

**Comment by musicus** [comment]
Yes, this is known (D3.js). Are you doing Unit Tests with or without browser? Are you using Jasmine?

**Comment by vee-L** [comment]
Jasmine, both with and wihout. I've changed my approach just now, I'll see if it works.

**Comment by musicus** [comment]
So, I'm assuming your changed approach worked?
