### ISSUE TITLE
Piano Roll

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/VIS-Ualizer#96]
Nothing happens when I open `Piano Roll` in Safari (or Chrome, Firefox). This may not be a bug and only has to be specified in `main.py`, but a default piano roll should be shown.

**Comment by vee-L** [comment]
The problems are because stuff got messed up/is missing from the merge when it shouldn't be. I'm doing a detailed check of everything to make sure it's ok and then I'll push this

**Comment by musicus** [comment]
That's why I asked to double check yesterday.
🎅
